name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: echo Hello1 
      shell: bash
    - id: random-number-generator
      run: echo Hello2
      shell: bash
    #- shell: bash
        #run: |
         # expr 1 + 1 > output.log
      #- name: Upload output file
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: output-log-file
      #    path: output.log
